### ISSUE TITLE
How does this relate to the kodi-recently-added custom integration?

### ISSUE THREAD

**Issue by groenmarsmannetje** [jtbgroup/kodi-media-sensors#1]
Does this mean that this also replaces the kodi-recently-added custom integration? 
Then that integration better should be marked as deprecated. 

I also do not see it mentioned as "dependency" in the [upcoming-media-card](https://github.com/custom-cards/upcoming-media-card) 

In my opinion forking is not always the best approach for life cycle management of a component. 
Only do it when you really have no other option. Did you consider a Pull Request on the original one?

**Comment by jtbgroup** [comment]
Hi, this is the continuity of the original project as the main developer did freeze his project. Have been in contact with him and this approach comes from him.

I won't touch the part of the code compatible with the upcoming-media-card. I will just add new features.
