### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by roumano** [jtbgroup/kodi-media-sensors#12]
**Describe the bug**
Error doing job: Task exception was never retrieved,
The integration is not working anymore

**To Reproduce**
1. Add the integration
2. Configure it
3. See error

**Expected behavior**
i expected it's not crash and able to use it.

**Screenshots**

**Home Assistant and Custom Component versions (please complete the following information):**
Home Assistant version: core-2022.3.5
Python Version:  3.10.2
kodi-recently-added component version: v2.0.5
Kodi Media Sensors for Home Assistant: v3.4.2

**Additional context**
The Backtrace
```
mars 20 12:34:36 rasp hass[19672]: 2022-03-20 12:34:36 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
mars 20 12:34:36 rasp hass[19672]: Traceback (most recent call last):
mars 20 12:34:36 rasp hass[19672]:   File "/data/homeassistant/.homeassistant/custom_components/kodi_media_sensors/entity_kodi_playlist.py", line 167, in __handle_event
mars 20 12:34:36 rasp hass[19672]:     self._force_update_state()
mars 20 12:34:36 rasp hass[19672]:   File "/data/homeassistant/.homeassistant/custom_components/kodi_media_sensors/entity_kodi_playlist.py", line 172, in _force_update_state
mars 20 12:34:36 rasp hass[19672]:     self.hass.async_create_task(self.async_update_ha_state(True))
mars 20 12:34:36 rasp hass[19672]: AttributeError: 'NoneType' object has no attribute 'async_create_task'
```

**Comment by jtbgroup** [comment]
should be ok with version 3.4.3
