### ISSUE TITLE
This integration will be broken when HA 2021.4 is released

### ISSUE THREAD

**Issue by raman325** [jtbgroup/kodi-media-sensors#13]
**Describe the bug**
HA 2021.4 removes `device_state_attributes` as an entity property which means the sensors return no data. To fix this, #11 needs to be merged.

For users who run into this before the PR gets merged, you can manually make these changes in your custom components folder to get things working again.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Home Assistant and Custom Component versions (please complete the following information):**
Home Assistant version:
kodi-recently-added component version:

**Additional context**

**Comment by jtbgroup** [comment]
Hi raman,

I'm running HA 2022.4 and the integration still works. But indeed, I see some errors in the logs. I'll check this.

**Comment by jtbgroup** [comment]
Hello, 
Beta version (3.4.3_b) is available in hacs. I did'nt merge your changes because there was a few modifications and it was easier for me to copy the changes rather than merge them. 
Let me know if everything works.

**Comment by raman325** [comment]
Here: https://github.com/jtbgroup/kodi-media-sensors/blob/develop/custom_components/kodi_media_sensors/entities.py#L125

And here: https://github.com/jtbgroup/kodi-media-sensors/blob/develop/custom_components/kodi_media_sensors/entities.py#L202

**Comment by jtbgroup** [comment]
damned... I just modified and built the 3.4.3_c

**Comment by raman325** [comment]
That resolved it! Separately I noticed this at the beginning of the list for the data attribute, not sure if it's an issue or not:
```
{"title_default": "$title", "line1_default": "$genres", "line2_default":
  "$release", "line3_default": "$rating - $runtime", "line4_default": "$studio",
  "icon": "mdi:eye-off"}, {"aired": "2022-02-25", "airdate":
  "2022-02-25T00:00:00Z", "flag": true, "genres": "Crime,Drama", "rating":
  "\u2605 7.1", "release": "$date", "runtime": 105, "title": "Movie Name",
  "studio": "Focus Features", "fanart": "http://url%252Ffanart.jpg",
  "poster":
  "http://url%252Fposter.jpg"}
```

Note that first entry, and then the `release` for the second entry is `$date`

If this is a real issue, I am happy to open a separate ticket to track it

**Comment by jtbgroup** [comment]
Great! Thank you for the help!

I suppose you speak about the __sensor.kodi_recently_added_movies__ or the __sensor.kodi_recently_added_tv__?
These sensors come from the original implementation (https://github.com/boralyl/kodi-recently-added). I kept those 2 sensors for compatibility reasons, but to be honnest, I don't use them. I use the 'search' sensor to get the recently added items (in combination with the search card), which give the same result.

**Comment by raman325** [comment]
In this case it was the recently added movies sensor but the behavior appears to be the same as recently added TV. Regardless, I understand your point about keeping compatibility. I will play with this myself and submit a PR if I can clean it up without breaking anything.

Thanks for resolving this issue! Can we get a non-beta release with the changes?

**Comment by jtbgroup** [comment]
I kept it because some cards (I don't use) need this structure of data. As I needed other cards for personal needs (search and playlist cards), I developed my own data structure with the "meta" part.

Of course, a non beta will be available in a few days. I always use a beta version a couple of days myself to be sure there is no regression bug introduced. I think I'll do that this weekend.

**Comment by raman325** [comment]
sounds great, thanks!
