### ISSUE TITLE
scrolling playlist

### ISSUE THREAD

**Issue by fax13** [jtbgroup/kodi-media-sensors#14]
hi guys,
as i am a daily kodi user over the years i was extremly enthousiast that kodi sensors were developed.
oveerall i am pleased except the fact that the playlists are not scrollable.
this means that when i use music plylists which contains a large amount of songs, the list in my view is extremly long.
therefore as in many other applications, a scrollable list would be a very welcome gesture.
what do you think, is that do-able?

**Comment by jtbgroup** [comment]
Hi, 
This feature is still in the list of enhancements of the playlist card; it's not linked to the sensors. 

Do you have an example of another card that would be scrollable? I searched a little bit, but didn't find how to do that. Not sure Lovelace permits it.

**Comment by fax13** [comment]
Hey Gautier, i will have a look in my HA if i find such a thing. As far i
know i didn't see that either. But let me check and i get back to you asap

**Comment by fax13** [comment]
hi again,
i've installetd the beta and the scroplling works as a charm!!!!
what a game changer! i thank you upfront for the effort that is made.
but... strangly enough only the playing song is highlighted as shown in the picture
![kodi now plying card](https://user-images.githubusercontent.com/76689575/174665757-317e9bb1-a9f0-437f-a939-30210f55f071.png)
any idea how that might happen?

**Comment by jtbgroup** [comment]
Hi, I close this request as the feature is ok. I created another issue for your problem. Please have a look at it as I need more information about your problem.
