### ISSUE TITLE
integration uses deprecated `async_get_registry`

### ISSUE THREAD

**Issue by mshuflin** [jtbgroup/kodi-media-sensors#18]
**Describe the bug**
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 2:19:44 PM (1 occurrences)
Last logged: 2:19:44 PM

Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom integration author for kodi_media_sensors using this method at custom_components/kodi_media_sensors/sensor.py, line 110: reg = await hass.helpers.entity_registry.async_get_registry()

Home Assistant 2022.8.6
Kodi Media Sensors 3.4.3

**Comment by jtbgroup** [comment]
modified.
