### ISSUE TITLE
Provide file path for media items

### ISSUE THREAD

**Issue by Rudd-O** [jtbgroup/kodi-media-sensors#20]
Currently the plugin provides the following attribute:

```
[{"album": "", "artist": [], "episode": 4, "genre": "Drama, Family, Romance", "id": 14811, "label": "Greek to Me", "season": 4, "thumbnail": "http://kodi:dumb leave toss 43rd alfer grok@10.250.7.3:8080/image/image%3A%2F%2Fhttps%253a%252f%252fartworks.thetvdb.com%252fbanners%252fepisodes%252f74936%252f158152.jpg%2F", "title": "Greek to Me", "track": -1, "type": "episode", "year": 1993}]
```

It would be great (and very helpful for automations) if each item could have the corresponding file path.

**Comment by Rudd-O** [comment]
Here: https://github.com/jtbgroup/kodi-media-sensors/blob/eeca206a386cfb47e83c8ff0a9e5b8f4d7553015/custom_components/kodi_media_sensors/const.py#L216

You want to add an additional parameter: `"file"`

That fixes the issue.

**Comment by Rudd-O** [comment]
https://github.com/jtbgroup/kodi-media-sensors/pull/21

**Comment by jtbgroup** [comment]
added in version 3.6.0
