### ISSUE TITLE
When music video is playing, attributes.meta does not have a "Currently playing" item

### ISSUE THREAD

**Issue by Rudd-O** [jtbgroup/kodi-media-sensors#22]
**Describe the bug**
Attributes.meta and attributes.data are present when a music video *not in the media database* is playing in Kodi, but `attributes.meta` has no `currently_playing` attribute in that case.  This makes it impossible for the playlist sensor to tell where in the playlist Kodi currently is.

**To Reproduce**
Play a video in Kodi that is not registered in the database.  E.g. a newly added music video before scanning, or a YT video shared from NewPipe.

**Expected behavior**
The video playlist meta attribute returned by the sensor should have a currently_playing, even if the video file does not have a database ID.  In that case there should be at least a fallback of a path instead.

**Comment by Rudd-O** [comment]
When item currently playing is not in database:

```
[{"update_time": "20220911160502029204", "sensor_entity_id": "sensor.kodi_media_sensor_playlist", "service_domain": "kodi_media_sensors", "playlist_id": 1, "playlist_type": "video"}]
```

When item currently playing IS in database:

```
[{"update_time": "20220911160535067040", "sensor_entity_id": "sensor.kodi_media_sensor_playlist", "service_domain": "kodi_media_sensors", "playlist_id": 1, "playlist_type": "video", "currently_playing": 1709}]
```

**Comment by Rudd-O** [comment]
Found the issue.  Hang on for bug report.

**Comment by Rudd-O** [comment]
https://github.com/jtbgroup/kodi-media-sensors/pull/23 Here is the fix.

**Comment by jtbgroup** [comment]
Hello,

I quickly checked with audio files and I get the same result. The integration is supposed to work with the libraries but indeed, why not integrate more use cases :-).

As the impact is general (all item types), I'll see if your pull request is the best approach; maybe I'll need to keep the ID as control for items in the library and the file as backup. 

In any case, I can't do that the coming days, but I promise it's on my todo list.

**Comment by Rudd-O** [comment]
This PR does not change the fact that we retrieve IDs for the currently playing file — we also retrieve filenames in addition, which is (I think) what you mean as well.
