### ISSUE TITLE
Kodi Media Sensors not able to handle more than 1 Kodi instance

### ISSUE THREAD

**Issue by wickedgalen** [jtbgroup/kodi-media-sensors#26]
**Is your feature request related to a problem? Please describe.**
Sort of.
Using 2 Kodi Players at home for now.

As I have added the Integration twice :

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:540
Integration: Sensor (documentation, issues)
First occurred: 8:14:31 AM (4 occurrences)
Last logged: 8:14:35 AM

Platform kodi_media_sensors does not generate unique IDs. ID kodi_media_sensor_search already exists - ignoring sensor.kodi_media_sensor_search
Platform kodi_media_sensors does not generate unique IDs. ID kodi_recently_added_tv already exists - ignoring sensor.kodi_recently_added_tv
Platform kodi_media_sensors does not generate unique IDs. ID kodi_recently_added_movies already exists - ignoring sensor.kodi_recently_added_movies
Platform kodi_media_sensors does not generate unique IDs. ID kodi_media_sensor_playlist already exists - ignoring sensor.kodi_media_sensor_playlist

**Describe the solution you'd like**

I would want to be able to have separate Kodi Media Sensors per Kodi Player due to different Libraries (Age restriction related) and /or profile changes.

**Describe alternatives you've considered**
I can't think of any in this case.

**Additional context**
![image](https://user-images.githubusercontent.com/81089200/218259207-a2d1cd6d-153f-4a61-919a-92580b642af1.png)

![image](https://user-images.githubusercontent.com/81089200/218259220-87b310f3-01a5-402d-8684-59b09f1a9686.png)

**Home Assistant and Custom Component versions (please complete the following information):**
Home Assistant version: latest to date, no newer updates available
kodi-recently-added component version: latest to date, no newer updates available

**Comment by jtbgroup** [comment]
Hi, I worked on a version 5.0.0 which is now in beta version. I think I solved it. Can you try and let me know if it's ok as I don't use multiple instance of kodi at home in real situation.

Attention you'll need to reconfigure the integration completely as using new ID break the links with previous configuration.

**Comment by wickedgalen** [comment]
Hi
sorry for the delay, I installed the beta now and I can confirm adding the integration creates new entities.
![image](https://user-images.githubusercontent.com/81089200/224509927-e33d2486-b793-4f6f-8e0b-adf37701694e.png)

Due to time issues I'll come back to you later.
Thank you already.

**Comment by jtbgroup** [comment]
Hi, I suppose this is working now. I close the request.
