### ISSUE TITLE
Loading error since updating to 2021.5.0

### ISSUE THREAD

**Issue by Darren-Hill** [jtbgroup/kodi-media-sensors#3]
**Describe the bug**
The integration fails to set up on start-up since updating to HA 2021.5.0 .
Gives log error (reproduced below) and lists as failed to set up under Configuration > Integrations

**To Reproduce**
1. Update to current HA version (2021.5.0) with sensors installed
2. Reboot

**Expected behavior**
Sensors to load and be functional (as they were in 2021.4.x).

**Home Assistant and Custom Component versions (please complete the following information):**
Home Assistant version: 2021.5.0 on Pi4
kodi-recently-added component version: 2.0.0 via HACS

**Additional context**
Log entry for the integration:

> Logger: homeassistant.config_entries
> Source: custom_components/kodi_media_sensors/__init__.py:33
> Integration: Kodi Media Sensors (documentation, issues)
> First occurred: 7:53:25 PM (1 occurrences)
> Last logged: 7:53:25 PM
> 
> Error setting up entry Kodi Media Sensors for kodi_media_sensors
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
>     result = await component.async_setup_entry(hass, self)  # type: ignore
>   File "/config/custom_components/kodi_media_sensors/__init__.py", line 33, in async_setup_entry
>     sensor_search = entry.data[CONF_SENSOR_SEARCH]
> KeyError: 'sensor_search'

**Comment by Darren-Hill** [comment]
Also had this log error appear:

> Logger: homeassistant.loader
> Source: loader.py:794
> First occurred: 8:26:38 PM (1 occurrences)
> Last logged: 8:26:38 PM
> 
> No 'version' key in the manifest file for custom integration 'kodi_media_sensors'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'kodi_media_sensors'

**Comment by Telmo** [comment]
having the same issue

```
Logger: homeassistant.config_entries
Source: custom_components/kodi_media_sensors/__init__.py:33
Integration: Kodi Media Sensors (documentation, issues)
First occurred: May 6, 2021, 12:12:10 PM (1 occurrences)
Last logged: May 6, 2021, 12:12:10 PM

Error setting up entry Kodi Media Sensors for kodi_media_sensors
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/kodi_media_sensors/__init__.py", line 33, in async_setup_entry
    sensor_search = entry.data[CONF_SENSOR_SEARCH]
KeyError: 'sensor_search'
```

**Comment by mshuflin** [comment]
Also the same issue

Logger: homeassistant.config_entries
Source: custom_components/kodi_media_sensors/__init__.py:33
Integration: Kodi Media Sensors (documentation, issues)
First occurred: 9:08:13 PM (1 occurrences)
Last logged: 9:08:13 PM

Error setting up entry Kodi Media Sensors for kodi_media_sensors
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/kodi_media_sensors/__init__.py", line 33, in async_setup_entry
    sensor_search = entry.data[CONF_SENSOR_SEARCH]
KeyError: 'sensor_search'

**Comment by jtbgroup** [comment]
Sorry, didn't see the issues.

Version problem should be ok with version 2.0.1.
I'm on the "KeyError: 'sensor_search'"

Did one of you tried an uninstall - install of the integration? I changed the name of the sensors;

**Comment by Darren-Hill** [comment]
Just got the update to 2.0.1, and all seems to be correctly working now.

**Comment by jtbgroup** [comment]
Thank you for you feedback, I'll post it on github


Le sam. 15 mai 2021 à 12:22, Darren-Hill ***@***.***> a
écrit :

**Comment by jtbgroup** [comment]
No more bad feedback. I close the bug.
