### ISSUE TITLE
Mix sensors from multiple instances to access pool sensor data

### ISSUE THREAD

**Issue by bcutter** [jtbgroup/kodi-media-sensors#4]
I have several KODI instances accessing the same media. Those instances run only for a certain time, randomly (no permanent TV KODI instance).
The sensors currently provided by the integration are tied to **one specific KODI instance/media player.**

Therefore when using cards like recently added episodes or movies (I do with upcoming media card) it may result in NO results shown at all because that KODI instance is not running currently. At the end the sensors and integration is almost useless unfortunately :-(

1) How can I merge things so my cards access the pool of KODI instances/media players?
2) What can this integration improve related to this use-case?
3) Any ideas to work around this?

At the end I want ONE sensor (for TV + movies) to update independently from the specific KODI media player (because as I said they´re all accessing the same media).

**Comment by jtbgroup** [comment]
Hi, 

When you say "At the end the sensors and integration is almost useless", I would add... "for your use case, and your use case is a very uncommon one" :-)

You can add the integration serveral times and pobably choose a different kodi instance for each install. I don't know the effect of it as I only run 1 kodi. There might be conflicts with the name of the entities, so after each install, I'd suggest to rename the sensors.

This being done, you'll have to program a custom card that can't read the data from the sensors and aggregate them. As far as I know, the upcoming media card only works with one sensor.

**Comment by bcutter** [comment]
> Hi, 
> 
> 
> 
> When you say "At the end the sensors and integration is almost useless", I would add... "for your use case, and your use case is a very uncommon one" :-)
> 
> 

Yes you're absolutely right :-)

Meanwhile I realized the integration is made for (or only fully usable when using)
a) ONE KODI instance
b) ideally running 24/7

So if the KODI instance is not running, the Home Assistant log is **flooded** with error messages (about one hundred per hour) which is a no go for me. I think I'll need to remove the integration because of this "pulling concept" - which has nothing to do with my initial FR.

![image](https://user-images.githubusercontent.com/13799156/118358809-dcd01d80-b580-11eb-828c-c83df107b292.jpeg)

Would be much smarter if
- the integration gets triggered by the media_player becoming active and only starts updating its sensor(s) than and
- stops updating its sensor(s) after the KODI instance is not available for a certain amount of time/update requests.

This would reduce the amount of errors significantly.

Feel free to close this issue or use my 2 cents as input for another issue/FR.

**Comment by jtbgroup** [comment]
Hi,

Thanks for your report. I didn't notice so many errors were reported as my Kodi runs constantly. I'll certainly check for that. I don't know if it's possible to change the sensor update frequence once the sensor is running and interpreting kodi events can lead to confusion sometimes.

**Comment by bcutter** [comment]
Proposal would be to listen for a media_player (KODI) becoming active and only start sensor update. No need to change sensor update interval (which alone would not be sufficient). But that´s another issue ;-)

**Comment by jtbgroup** [comment]
Not that easy. Not sure Kodi sends an event when it starts (or becomes active after idle). So how to know if the status 'not reachable' of kodi is due to inactivity (which would be an info) or network issue (which would be an error)?

**Comment by bcutter** [comment]
Well my Home Assistant has access to the KODI instance and exposes a media_player entity. That entity **already KNOWS** when KODI becomes available and what state it is in (idle, playing, paused etc.).
Way to easy (on a HA automation level) to use that information as trigger to start sensor update. For the other way around (KODI not reachable): set a timeout.

That would be already a lot better than the current polling mechanism I think.

**Comment by bcutter** [comment]
> 
> 
> Well my Home Assistant has access to the KODI instance and exposes a media_player entity. That entity **already KNOWS** when KODI becomes available and what state it is in (idle, playing, paused etc.).
> Way to easy (on a HA automation level) to use that information as trigger to start sensor update. For the other way around (KODI not reachable): set a timeout.
> 
> That would be already a lot better than the current polling mechanism I think.

Et voilá: here we go. Exactly I was looking for.

https://www.home-assistant.io/blog/2021/06/02/release-20216/#disable-polling-updates-on-any-integration

**Comment by jtbgroup** [comment]
yes, I saw that too! you can probably stop the integration polling when your kodi is off using integration. I'm happy, I don't have to implement it! :-)

**Comment by bcutter** [comment]
As this just fixes the constant polling and log flooding issue (still working on it, cause disabling polling as newly introduced is just easily possible for integrations managed using the UI currently) - which was a sidenote of this issue - the main issue still exists. Not sure why it has been closed.

**Comment by jtbgroup** [comment]
It has been closed because the actual implementation is based on sensors and those objects poll the devices constantly and update their values.  This is the standard behavior of a sensor. 

If you consider kodi running as a requirement (which it is for this integration), it's normal you get error messages when it doesn't find your multimedia. You can always change the log level for this integration if you don't want to see the logs.

For the moment, the integration fits my needs and the standard way to use kodi. I have no time now to redesign it, even if I would like to. Contribution is  welcome!

**Comment by jtbgroup** [comment]
Hi, 

I rewrote some part of the code to use events from kodi instead of polling the mediaplayer. A Beta version is available on branch [develop](https://github.com/jtbgroup/kodi-media-sensors/tree/develop). I still need a few days to test it, but you already can try it. The cards were also adapted (branches develop).
