### ISSUE TITLE
Traceback AttributeError: 'NoneType' object has no attribute 'add_job'

### ISSUE THREAD

**Issue by roumano** [jtbgroup/kodi-media-sensors#8]
**Describe the bug**
On my logs i recurrently see this error loop : 
```
janv. 21 15:02:15 rasp hass[475]: 2022-01-21 15:02:15 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
janv. 21 15:02:15 rasp hass[475]: Traceback (most recent call last):
janv. 21 15:02:15 rasp hass[475]:   File "/data/homeassistant/.homeassistant/custom_components/kodi_media_sensors/entity_kodi_playlist.py", line 155, in __handle_event
janv. 21 15:02:15 rasp hass[475]:     self.schedule_update_ha_state()
janv. 21 15:02:15 rasp hass[475]:   File "/data/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 643, in schedule_update_ha_state
janv. 21 15:02:15 rasp hass[475]:     self.hass.add_job(self.async_update_ha_state(force_refresh))  # type: ignore
janv. 21 15:02:15 rasp hass[475]: AttributeError: 'NoneType' object has no attribute 'add_job'
```

**Expected behavior**
i can use this custom_components, but i get many Traceback

25 since 15h to be exact : 
```
# journalctl -r |grep -c '/data/homeassistant/.homeassistant/custom_components/kodi_media_sensors/entity_kodi_playlist.py'
25
```

**Home Assistant and Custom Component versions (please complete the following information):**
Home Assistant version: core-2021.12.10
kodi-recently-added component version: 3.3.0 
Python : 3.10.2

**Comment by jtbgroup** [comment]
Thanks for reporting. I also saw that error sometimes but I haven't been able to determine the origin. As it worked, I didn't dig further yet. I'll do it for the next release.

**Comment by jtbgroup** [comment]
Hi, I changed a little bit the code and didn't see the error anymore, but you never know... To be honest, I don't really understand why this error appeared. 

Anyway, there's beta release (3.4.0_b) you can test using HACS. It contains the feature to add an item to the position you want in the playlist.. There is also a new version of the playlist and search card.

**Comment by jtbgroup** [comment]
I close this as I didn't see the error anymore.
