### ISSUE TITLE
Provide image proxy for thumbnails

### ISSUE THREAD

**Issue by geiseri** [jtbgroup/kodi-media-sensors#9]
It looks like the kodi integration for the media player will provide an image proxy url to the internal resource.   It might help with the mixing of http/https when you have ha behind an ingress, but kodi is just an ip address.  See: [media player component](https://github.com/home-assistant/core/blob/ffe821a1f7602a5c3e5bc4ca395358d4838873ff/homeassistant/components/media_player/__init__.py#L1041)  I am not sure how that would apply since there would be quite a few images vs a single one.  Maybe the "hash" of the URL could be used to identify it.

**Comment by jtbgroup** [comment]
Hi geiseri,

Sorry for the late answer. I don't get notified of the new issues on github. I'll have to check that.

The image proxy seems indeed interesting. I'll try to see if I can use it in the code.

**Comment by geiseri** [comment]
lol, np.  if this was the worst of my problems I would be a lucky man!

**Comment by jtbgroup** [comment]
This has been fixed in the version 4.5.0 of the playlist card.
